version: '3.8'

services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      - ./public/uploads:/app/next-app/public/uploads
      - ./src/data:/app/next-app/src/data
    restart: unless-stopped
    networks:
      - shared

networks:
  shared:
    external: true